package game;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import client.Client;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JButton;

/**
 *
 * Login_page'de rakip bulunana kadar bu sayfa açılmamalı.
 *
 * @author iremayvaz
 */
public class Game extends javax.swing.JFrame {

    public static Game game;
    public static Map map;

    public static Player oyuncu;
    public static boolean isYourTurn; // sıra benim mi

    public static Player rakip;

    public static ArrayList<Territory> secilenBolgeler = new ArrayList<>(); // buton selected

    public Game() throws IOException {
        initComponents();
    }

    public Game(Map gelenHarita) throws IOException {
        initComponents();
        Game.game = this;
        Game.map = new Map();
        Game.map.all_territories = gelenHarita.all_territories;

        System.out.println("Benim oyuncu id: " + Game.oyuncu.id);

        setTerritoryButtons(Game.map.all_territories);

        haritaYerlestir(Game.map.all_territories);

        addAction(Game.map.all_territories);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pnl_harita = new javax.swing.JPanel();
        lbl_you = new javax.swing.JLabel();
        lbl_localClient = new javax.swing.JLabel();
        lbl_opponent = new javax.swing.JLabel();
        lbl_otherClient = new javax.swing.JLabel();
        lbl_state = new javax.swing.JLabel();
        btn_attack = new javax.swing.JButton();
        btn_deploy = new javax.swing.JButton();
        btn_skip = new javax.swing.JButton();
        btn_kuzeyAmerika = new javax.swing.JButton();
        btn_guneyAmerika = new javax.swing.JButton();
        btn_avrupa = new javax.swing.JButton();
        btn_afrika = new javax.swing.JButton();
        btn_asya = new javax.swing.JButton();
        btn_avustralya = new javax.swing.JButton();
        lbl_harita = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_harita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_you.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbl_you.setForeground(new java.awt.Color(255, 255, 255));
        lbl_you.setText("YOU :");
        pnl_harita.add(lbl_you, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 50, 40));

        lbl_localClient.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbl_localClient.setForeground(new java.awt.Color(0, 255, 0));
        pnl_harita.add(lbl_localClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 120, 40));

        lbl_opponent.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbl_opponent.setForeground(new java.awt.Color(255, 255, 255));
        lbl_opponent.setText(": OPPONENT");
        pnl_harita.add(lbl_opponent, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 30, 120, 40));

        lbl_otherClient.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbl_otherClient.setForeground(new java.awt.Color(255, 0, 0));
        pnl_harita.add(lbl_otherClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 27, 130, 40));

        lbl_state.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbl_state.setForeground(new java.awt.Color(255, 255, 255));
        pnl_harita.add(lbl_state, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 190, 30));

        btn_attack.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_attack.setForeground(new java.awt.Color(153, 204, 255));
        btn_attack.setText("ATTACK");
        btn_attack.setBorderPainted(false);
        btn_attack.setContentAreaFilled(false);
        btn_attack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_attack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attackActionPerformed(evt);
            }
        });
        pnl_harita.add(btn_attack, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 280, -1, -1));

        btn_deploy.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_deploy.setForeground(new java.awt.Color(153, 204, 255));
        btn_deploy.setText("DEPLOY");
        btn_deploy.setBorderPainted(false);
        btn_deploy.setContentAreaFilled(false);
        btn_deploy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_deploy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deployActionPerformed(evt);
            }
        });
        pnl_harita.add(btn_deploy, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 320, -1, -1));

        btn_skip.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btn_skip.setForeground(new java.awt.Color(204, 204, 204));
        btn_skip.setText("SKIP");
        btn_skip.setBorderPainted(false);
        btn_skip.setContentAreaFilled(false);
        btn_skip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_skip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_skipActionPerformed(evt);
            }
        });
        pnl_harita.add(btn_skip, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 360, -1, -1));

        btn_kuzeyAmerika.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        btn_kuzeyAmerika.setForeground(new java.awt.Color(255, 255, 255));
        btn_kuzeyAmerika.setText("0");
        btn_kuzeyAmerika.setBorderPainted(false);
        btn_kuzeyAmerika.setContentAreaFilled(false);
        btn_kuzeyAmerika.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_harita.add(btn_kuzeyAmerika, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 215, 100, 120));

        btn_guneyAmerika.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        btn_guneyAmerika.setForeground(new java.awt.Color(255, 255, 255));
        btn_guneyAmerika.setText("0");
        btn_guneyAmerika.setBorderPainted(false);
        btn_guneyAmerika.setContentAreaFilled(false);
        btn_guneyAmerika.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_harita.add(btn_guneyAmerika, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 465, 110, 130));

        btn_avrupa.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        btn_avrupa.setForeground(new java.awt.Color(255, 255, 255));
        btn_avrupa.setText("0");
        btn_avrupa.setBorderPainted(false);
        btn_avrupa.setContentAreaFilled(false);
        btn_avrupa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_harita.add(btn_avrupa, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 135, 210, 150));

        btn_afrika.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        btn_afrika.setForeground(new java.awt.Color(255, 255, 255));
        btn_afrika.setText("0");
        btn_afrika.setBorderPainted(false);
        btn_afrika.setContentAreaFilled(false);
        btn_afrika.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_harita.add(btn_afrika, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 90, 110));

        btn_asya.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        btn_asya.setForeground(new java.awt.Color(255, 255, 255));
        btn_asya.setText("0");
        btn_asya.setBorderPainted(false);
        btn_asya.setContentAreaFilled(false);
        btn_asya.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_harita.add(btn_asya, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 210, 190));

        btn_avustralya.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        btn_avustralya.setForeground(new java.awt.Color(255, 255, 255));
        btn_avustralya.setText("0");
        btn_avustralya.setBorderPainted(false);
        btn_avustralya.setContentAreaFilled(false);
        btn_avustralya.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnl_harita.add(btn_avustralya, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 505, 140, 120));

        lbl_harita.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        lbl_harita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/harita.png"))); // NOI18N
        pnl_harita.add(lbl_harita, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton2.setText("jButton2");
        pnl_harita.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_harita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_harita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_attackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attackActionPerformed
        if (Game.secilenBolgeler.isEmpty()) { // Seçim yapılamamışsa
            System.out.println("liste boş");
        } else if (Game.secilenBolgeler.size() == 1) { // Seçim eksikse
            System.out.println("liste boş");
            Game.secilenBolgeler.clear();
        } else {
            Territory from = Game.secilenBolgeler.get(0);
            Territory to = Game.secilenBolgeler.get(1);

            if (to.playerID != Game.oyuncu.id) { // saldırı koşulu sağlanmış

                System.out.println("secilen bolgeler");
                for (Territory t : Game.secilenBolgeler) {
                    System.out.println(t.name + ":" + t.totalTroop);
                }

                // Saldırıyı gerçekleştir
                boolean saldiriBasarili = from.attack(to);

                if (saldiriBasarili) {
                    Game.secilenBolgeler.clear();
                    // GUNCEL VERİLER
                    Game.secilenBolgeler.add(from);
                    Game.secilenBolgeler.add(to);

                    try {
                        // GUNCEL VERİLER SERVER'A
                        Client.SendMessageToServer(new Message(Message.Type.ATTACK, Game.secilenBolgeler));
                    } catch (IOException ex) {
                        Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    System.out.println("Saldiri basarili olamadi!");
                }
            } else {
                System.out.println("kendine saldıramazsın!");
            }
            // Listeyi temizle
            Game.secilenBolgeler.clear();
        }
    }//GEN-LAST:event_btn_attackActionPerformed

    private void btn_skipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_skipActionPerformed
        try {
            // Listeyi temizle
            Game.secilenBolgeler.clear();
            Client.SendMessageToServer(new Message(Message.Type.SKIP_TURN, Game.oyuncu.id));
        } catch (IOException ex) {
            Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_skipActionPerformed

    private void btn_deployActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deployActionPerformed
        if (Game.secilenBolgeler.isEmpty()) { // Seçim yapılamamışsa
            System.out.println("liste boş");
        } else if (Game.secilenBolgeler.size() == 1) { // Seçim eksikse
            System.out.println("liste boş");
            Game.secilenBolgeler.clear();
        } else {
            Territory from = Game.secilenBolgeler.get(0);
            Territory to = Game.secilenBolgeler.get(1);

            if (to.playerID == Game.oyuncu.id) {

                System.out.println("secilen bolgeler");
                for (Territory t : Game.secilenBolgeler) {
                    System.out.println(t.name + ":" + t.totalTroop);
                }

                // Saldırıyı gerçekleştir
                boolean konuslandirmaBasarili = from.moveTroops(to);

                if (konuslandirmaBasarili) {
                    Game.secilenBolgeler.clear();
                    // GUNCEL VERİLER
                    Game.secilenBolgeler.add(from);
                    Game.secilenBolgeler.add(to);

                    try {
                        // GUNCEL VERİLER SERVER'A
                        Client.SendMessageToServer(new Message(Message.Type.DEPLOY, Game.secilenBolgeler));
                    } catch (IOException ex) {
                        Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    System.out.println("Yeniden konuşlandırma basarili olamadi!");
                }
            } else { // yeniden konuşlandırma koşulu sağlanmış
                System.out.println("rakibe asker taşıyamazsın!");
            }
            // Listeyi temizle
            Game.secilenBolgeler.clear();
        }
    }//GEN-LAST:event_btn_deployActionPerformed

    public JButton getTerritoryByButton(String bolgeAdi) { // Bölge butonlarını bulma
        for (Territory t : Game.map.all_territories) {
            if (t.name.equals(bolgeAdi)) {
                return t.bolge_butonu;
            }
        }
        return null;
    }

    public void setTerritoryButtons(ArrayList<Territory> guncelHarita) { // Bölge butonlarını bulma
        // Territory'leri butonlarla eşle
        for (Territory t : guncelHarita) {
            switch (t.name) {
                case "Afrika":
                    t.setButton(btn_afrika);
                    break;
                case "Asya":
                    t.setButton(btn_asya);
                    break;
                case "Avrupa":
                    t.setButton(btn_avrupa);
                    break;
                case "Avustralya":
                    t.setButton(btn_avustralya);
                    break;
                case "Güney Amerika":
                    t.setButton(btn_guneyAmerika);
                    break;
                case "Kuzey Amerika":
                    t.setButton(btn_kuzeyAmerika);
                    break;
            }

        }
    }

    public void haritaYerlestir(ArrayList<Territory> guncelHarita) {
        JButton btn;
        // Territory'leri oyuncularla eşle
        for (Territory t : guncelHarita) {
            btn = Game.game.getTerritoryByButton(t.name);
            // Bölgelerin asker sayılarını frame'de göster
            btn.setText(String.valueOf(t.totalTroop));

            if (t.playerID == Game.oyuncu.id) { // her oyuncu kendi bölgelerini görmeli
                if (!Game.oyuncu.territories.contains(t)) {
                    Game.oyuncu.territories.add(t);
                    t.owner = Game.oyuncu;
                }
                btn.setForeground(Color.green); // kendi bölgeleri yeşil
            } else {
                if (!Game.rakip.territories.contains(t)) {
                    Game.rakip.territories.add(t);
                    t.owner = Game.rakip;
                }
                btn.setForeground(Color.red); // rakip bölgeler kırmızı
            }
        }

    }

    public void addAction(ArrayList<Territory> guncelHarita) {
        JButton btn;
        // Bölge seçimleri için
        for (Territory t : guncelHarita) {
            btn = Game.game.getTerritoryByButton(t.name);
            btn.addActionListener(e -> {
                // daha hic bolge secilmedi
                if (Game.secilenBolgeler.isEmpty()) {
                    // ilk secim kendi bölgesi olmalı ve geride 1 asker bırakabilmeli
                    if (t.playerID == Game.oyuncu.id && t.totalTroop > 1) {
                        Game.secilenBolgeler.add(t);
                    } else {
                        JOptionPane.showMessageDialog(pnl_harita, "FIRST SELECT FROM YOUR TERRITORIES"
                                + "\nWHICH HAS MORE THAN 1 TROOP!",
                                "WARNING", JOptionPane.WARNING_MESSAGE);
                    }
                    // 2. bölge karşıdan olsun
                } else if (Game.secilenBolgeler.size() == 1) {
                    Game.secilenBolgeler.add(t);
                    // 2 den fazla seçilemez
                } else {
                    JOptionPane.showMessageDialog(pnl_harita, "YOU CANNOT SELECT MORE THAN 2 TERRITORY TO ATTACK!",
                            "WARNING", JOptionPane.WARNING_MESSAGE);
                }

            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Game().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_afrika;
    private javax.swing.JButton btn_asya;
    public javax.swing.JButton btn_attack;
    public javax.swing.JButton btn_avrupa;
    public javax.swing.JButton btn_avustralya;
    private javax.swing.JButton btn_deploy;
    public javax.swing.JButton btn_guneyAmerika;
    public javax.swing.JButton btn_kuzeyAmerika;
    private javax.swing.JButton btn_skip;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel lbl_harita;
    public javax.swing.JLabel lbl_localClient;
    private javax.swing.JLabel lbl_opponent;
    public javax.swing.JLabel lbl_otherClient;
    public javax.swing.JLabel lbl_state;
    private javax.swing.JLabel lbl_you;
    private javax.swing.JPanel pnl_harita;
    // End of variables declaration//GEN-END:variables
}
