/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package game;

import client.Client;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author iremayvaz
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login_page
     */
    public static Login login;
    public static boolean opponentFound;

    public Login() throws IOException {

        initComponents();
        lbl_state.setVisible(false);
        Login.login = this; // başka sınıflardan Frame'e tamamiyle erişmek için

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_login = new javax.swing.JPanel();
        lbl_icon = new javax.swing.JLabel();
        txt_gamer_name = new javax.swing.JTextField();
        btn_giris = new javax.swing.JButton();
        lbl_giris = new javax.swing.JLabel();
        lbl_login = new javax.swing.JLabel();
        lbl_state = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_login.setBackground(new java.awt.Color(0, 0, 0));

        lbl_icon.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        lbl_icon.setForeground(new java.awt.Color(255, 255, 255));
        lbl_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/header.jpg"))); // NOI18N

        btn_giris.setBackground(new java.awt.Color(0, 204, 255));
        btn_giris.setText("Giriş Yap");
        btn_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisActionPerformed(evt);
            }
        });

        lbl_giris.setForeground(new java.awt.Color(255, 255, 255));
        lbl_giris.setText("Oyuncu adı giriniz:");

        lbl_login.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        lbl_login.setForeground(new java.awt.Color(255, 255, 255));
        lbl_login.setText("RISK'E HOŞGELDİNİZ!");

        lbl_state.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        lbl_state.setForeground(new java.awt.Color(204, 204, 204));
        lbl_state.setText("Rakip oyuncu bekleniyor...");

        javax.swing.GroupLayout pnl_loginLayout = new javax.swing.GroupLayout(pnl_login);
        pnl_login.setLayout(pnl_loginLayout);
        pnl_loginLayout.setHorizontalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_loginLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lbl_login))
                    .addGroup(pnl_loginLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_state)
                            .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnl_loginLayout.createSequentialGroup()
                                    .addComponent(lbl_giris)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_gamer_name, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_giris))
                                .addComponent(lbl_icon)))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        pnl_loginLayout.setVerticalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbl_icon)
                .addGap(18, 18, 18)
                .addComponent(lbl_login)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_giris)
                    .addComponent(txt_gamer_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_giris))
                .addGap(18, 18, 18)
                .addComponent(lbl_state)
                .addGap(11, 11, 11))
        );

        txt_gamer_name.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girisActionPerformed
        try {
            Client.Connect("13.53.77.86", 6000);
            lbl_state.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Timer ile opponentFound kontrolü (Main UI thread'i donmaz!)
        new javax.swing.Timer(500, e -> {
            if (Login.opponentFound) {
                lbl_state.setText("Rakip bulundu. Oyun başlıyor!");
                ((javax.swing.Timer) e.getSource()).stop(); // Timer'ı durdur
                System.out.println("logHarita oluşturuldu. Oyun başlıyor!");
            }
        }).start();
    }//GEN-LAST:event_btn_girisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Login().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_giris;
    private javax.swing.JLabel lbl_giris;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_state;
    private javax.swing.JPanel pnl_login;
    public javax.swing.JTextField txt_gamer_name;
    // End of variables declaration//GEN-END:variables
}
